"""
SyncMap and SyncPoint models.

A SyncMap is the bridge between ebook text and audiobook timestamps.
It contains a list of SyncPoints, each mapping one EPUB sentence
to an audio time range.
"""

from datetime import datetime
from sqlalchemy import String, DateTime, Integer, ForeignKey, Text, Float
from sqlalchemy.orm import Mapped, mapped_column, relationship

from database import Base
from utils import utcnow


class SyncMap(Base):
    """
    The mapping between an ebook's text and its audiobook's timestamps.
    Generated by the transcription + alignment pipeline.
    One SyncMap per BookPair.
    """

    __tablename__ = "sync_maps"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    book_pair_id: Mapped[int] = mapped_column(
        ForeignKey("book_pairs.id"), unique=True, nullable=False
    )
    version: Mapped[int] = mapped_column(Integer, default=1)
    total_sentences: Mapped[int] = mapped_column(Integer, default=0)
    total_chapters: Mapped[int] = mapped_column(Integer, default=0)
    #: Composite hash (`services.file_hash`) of the ebook file this map was
    #: aligned against — the map's provenance (issue #295). A map whose stored
    #: hash no longer matches the file on disk describes a *different* document:
    #: its sentence coordinates resolve to text the reader will never find.
    #: NULL means the map predates this column — unknown provenance, not
    #: healthy; the drift audit falls back to sampling its previews.
    epub_file_hash: Mapped[str] = mapped_column(String(64), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=utcnow, nullable=False
    )

    # Relationships
    book_pair = relationship("BookPair", back_populates="sync_map")
    sync_points = relationship(
        "SyncPoint", back_populates="sync_map",
        cascade="all, delete-orphan",
        order_by="SyncPoint.epub_chapter, SyncPoint.epub_sentence_index",
    )

    def __repr__(self) -> str:
        return (
            f"<SyncMap(id={self.id}, pair={self.book_pair_id}, "
            f"sentences={self.total_sentences})>"
        )


class SyncPoint(Base):
    """
    A single alignment point: one EPUB sentence mapped to an audio time range.

    Attributes:
        epub_chapter: Chapter index (0-based)
        epub_sentence_index: Sentence index within the chapter (0-based)
        epub_text_preview: First 200 chars of the sentence for debugging
        audio_start_ms: Audio start timestamp in milliseconds
        audio_end_ms: Audio end timestamp in milliseconds
        audio_text: The transcribed text that corresponds to this time range, user editable.
    """

    __tablename__ = "sync_points"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    sync_map_id: Mapped[int] = mapped_column(
        ForeignKey("sync_maps.id"), nullable=False, index=True
    )
    epub_chapter: Mapped[int] = mapped_column(Integer, nullable=False)
    epub_sentence_index: Mapped[int] = mapped_column(Integer, nullable=False)
    epub_text_preview: Mapped[str] = mapped_column(String(200), nullable=True)
    audio_start_ms: Mapped[int] = mapped_column(Integer, nullable=False)
    audio_end_ms: Mapped[int] = mapped_column(Integer, nullable=False)
    audio_text: Mapped[str] = mapped_column(Text, nullable=True)
    # Alignment confidence 0..1; 0 means interpolated (not directly matched)
    confidence: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    # Relationships
    sync_map = relationship("SyncMap", back_populates="sync_points")

    def __repr__(self) -> str:
        return (
            f"<SyncPoint(ch={self.epub_chapter}, s={self.epub_sentence_index}, "
            f"audio={self.audio_start_ms}-{self.audio_end_ms}ms)>"
        )
