import kotlinx.kover.gradle.plugin.dsl.CoverageUnit
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.util.Properties

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.plugin.compose")
    id("com.google.dagger.hilt.android")
    id("com.google.devtools.ksp")
    id("org.jetbrains.kotlin.plugin.serialization")
    id("org.jetbrains.kotlinx.kover")
}

// ---------------------------------------------------------------------------
// Machine-local build settings (issue #58)
//
// Nothing that identifies one developer's machine — a server hostname, a LAN
// address — belongs in a committed file. These settings are read from, in order:
//
//   1. Gradle properties          (-Pname=value on the command line, or
//                                  ~/.gradle/gradle.properties) — so CI and
//                                  one-off builds can override
//   2. android/local.properties   (gitignored, the conventional Android home for
//                                  machine-specific config) — the everyday place
//
// and default to empty, so a clean clone builds something generic.
// `server/tests/test_android_no_personal_hosts.py` fails the test suite if a
// personal host creeps back into the committed sources.
// ---------------------------------------------------------------------------
val localProperties = Properties().apply {
    val file = rootProject.file("local.properties")
    if (file.exists()) file.inputStream().use { load(it) }
}

fun tandemSetting(name: String): String =
    providers.gradleProperty(name).orNull ?: localProperties.getProperty(name) ?: ""

/**
 * Extra hosts allowed to serve plain HTTP, on top of the loopback/emulator
 * entries every build gets. Comma-separated; hostnames or literal IPs.
 *
 * Android's network security config matches hostnames, not CIDR ranges, so
 * "my whole LAN" is not expressible — each host has to be listed by name.
 */
val extraCleartextHosts: List<String> =
    tandemSetting("tandem.cleartextHosts")
        .split(",")
        .map { it.trim() }
        .filter { it.isNotEmpty() }

/**
 * Writes `res/xml/network_security_config.xml`. Generated rather than committed
 * so the allowlist can carry a developer's LAN host without that host ending up
 * in the repo.
 */
abstract class GenerateNetworkSecurityConfig : DefaultTask() {
    @get:Input
    abstract val extraHosts: ListProperty<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        // trimIndent() is applied to the template *before* the hosts are spliced
        // in: interpolating first would change the common indent it computes and
        // push the XML declaration off column 0, which is invalid XML.
        val template = """
            <?xml version="1.0" encoding="utf-8"?>
            <!--
              GENERATED by the generateNetworkSecurityConfig Gradle task — do not edit.
              Extra hosts come from the `tandem.cleartextHosts` build setting; see the
              comment at the top of app/build.gradle.kts and docs/android.md.
            -->
            <network-security-config>
                <domain-config cleartextTrafficPermitted="true">
                    <!-- Android emulator's alias for the host machine -->
                    <domain includeSubdomains="false">10.0.2.2</domain>
                    <!-- Loopback, for a device forwarding to a local server -->
                    <domain includeSubdomains="false">127.0.0.1</domain>
                    <domain includeSubdomains="false">localhost</domain>@EXTRA_HOSTS@
                </domain-config>
            </network-security-config>
        """.trimIndent() + "\n"

        val extra = extraHosts.get().joinToString("") {
            "\n        <domain includeSubdomains=\"false\">$it</domain>"
        }
        val xmlDir = outputDir.get().asFile.resolve("xml")
        xmlDir.mkdirs()
        xmlDir.resolve("network_security_config.xml")
            .writeText(template.replace("@EXTRA_HOSTS@", extra))
    }
}

val generateNetworkSecurityConfig =
    tasks.register<GenerateNetworkSecurityConfig>("generateNetworkSecurityConfig") {
        description = "Generates res/xml/network_security_config.xml from tandem.cleartextHosts."
        extraHosts.set(extraCleartextHosts)
    }

androidComponents {
    onVariants { variant ->
        variant.sources.res?.addGeneratedSourceDirectory(
            generateNetworkSecurityConfig,
            GenerateNetworkSecurityConfig::outputDir,
        )
    }
}

android {
    namespace = "com.booksync"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.booksync"
        minSdk = 26
        // Pinned, not inherited from compileSdk (issue #148). targetSdk is a
        // behaviour switch — permissions, foreground-service rules, edge-to-edge,
        // orientation handling all change with it — so a compileSdk bump made for
        // an unrelated reason must not silently move it. Play also raises the
        // floor for new apps and updates every year (API 36 from 2026-08-31):
        // https://developer.android.com/google/play/requirements/target-sdk
        targetSdk = 36
        versionCode = 1
        versionName = "0.1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        // Server the app starts on before the user configures one. Empty by
        // default so a clean clone doesn't ship anyone's personal host (issue
        // #58) — the login screen then opens with the Server URL field visible.
        // Set it for your own builds via the machine-local settings above:
        //   tandem.defaultServerUrl=https://tandem.example.com
        buildConfigField(
            "String",
            "DEFAULT_SERVER_URL",
            "\"${tandemSetting("tandem.defaultServerUrl")}\"",
        )
    }

    // Room schema export (issue #168): with exportSchema = true on
    // BookSyncDatabase, each build writes app/schemas/<db>/<version>.json —
    // commit it, so schema changes are reviewable and MigrationTestHelper
    // tests are possible.
    ksp {
        arg("room.schemaLocation", "$projectDir/schemas")
    }

    // Play needs an .aab signed with an upload key, and there was no way to
    // produce one (issue #144). The four values live in android/local.properties,
    // which is gitignored — the keystore itself must stay outside the checkout
    // entirely, because a Play upload key cannot be rotated without Google's help.
    //
    //   tandem.signing.storeFile=/absolute/path/to/tandem-upload.jks
    //   tandem.signing.storePassword=...
    //   tandem.signing.keyAlias=upload
    //   tandem.signing.keyPassword=...
    //
    // Absent on a clean clone, and that has to keep working: the config is only
    // *applied* below when the keystore actually resolves, so `bundleRelease`
    // still succeeds unsigned in CI and for a fresh contributor.
    val releaseKeystore = tandemSetting("tandem.signing.storeFile")
        .takeIf { it.isNotBlank() }
        ?.let { file(it) }
        ?.takeIf { it.exists() }

    signingConfigs {
        create("release") {
            if (releaseKeystore != null) {
                storeFile = releaseKeystore
                storePassword = tandemSetting("tandem.signing.storePassword")
                keyAlias = tandemSetting("tandem.signing.keyAlias")
                keyPassword = tandemSetting("tandem.signing.keyPassword")
            }
        }
    }

    buildTypes {
        release {
            // Only when a keystore is actually present; see above.
            if (releaseKeystore != null) {
                signingConfig = signingConfigs.getByName("release")
            }
            isMinifyEnabled = true
            // No-op without minification, real savings with it (issue #145).
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        isCoreLibraryDesugaringEnabled = true
    }

    kotlin {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    testOptions {
        // JVM unit tests link against a stub android.jar whose methods throw by default.
        // Returning defaults instead keeps ViewModel tests from blowing up on incidental
        // framework calls (android.util.Log and friends) they aren't asserting on.
        unitTests.isReturnDefaultValues = true
    }
}

dependencies {
    // Core Android
    implementation("androidx.core:core-ktx:1.15.0")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.7")
    implementation("androidx.activity:activity-compose:1.9.3")
    implementation("androidx.appcompat:appcompat:1.7.0")
    implementation("com.google.android.material:material:1.12.0")

    // Compose
    implementation(platform("androidx.compose:compose-bom:2025.05.00"))
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-graphics")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material-icons-extended")
    implementation("androidx.navigation:navigation-compose:2.8.4")

    // Hilt (Dependency Injection)
    implementation("com.google.dagger:hilt-android:2.59")
    ksp("com.google.dagger:hilt-compiler:2.59")
    implementation("androidx.hilt:hilt-navigation-compose:1.2.0")

    // Networking (Retrofit + OkHttp)
    implementation("com.squareup.retrofit2:retrofit:2.11.0")
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    implementation("com.squareup.okhttp3:logging-interceptor:4.12.0")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")
    implementation("com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:1.0.0")

    // Room (Local Database)
    implementation("androidx.room:room-runtime:2.8.4")
    implementation("androidx.room:room-ktx:2.8.4")
    ksp("androidx.room:room-compiler:2.8.4")

    // Media3 / ExoPlayer (Audio Playback)
    implementation("androidx.media3:media3-exoplayer:1.7.1")
    implementation("androidx.media3:media3-session:1.7.1")
    implementation("androidx.media3:media3-ui:1.7.1")
    implementation("androidx.media3:media3-cast:1.7.1")
    // Lets ExoPlayer stream through the app's own authenticated OkHttp client, so
    // AuthInterceptor supplies the Bearer header and TokenAuthenticator refreshes a
    // 401 mid-stream — no media token in the URL (issue #171). Same version as the
    // rest of Media3; mixing versions across media3 artifacts is unsupported.
    implementation("androidx.media3:media3-datasource-okhttp:1.7.1")

    // Google Cast Framework (Chromecast)
    implementation("com.google.android.gms:play-services-cast-framework:21.5.0")

    // Embedded HTTP server — serves locally-downloaded audiobooks to the Cast receiver over the
    // LAN. Avoids relying on public DNS for tandem.lafuenti.com (Google Home Mini hardcodes 8.8.8.8
    // and ignores the DHCP DNS, so it can't resolve a LAN-only domain).
    implementation("org.nanohttpd:nanohttpd:2.3.1")

    // WorkManager (Offline Sync)
    implementation("androidx.work:work-runtime-ktx:2.10.0")
    implementation("androidx.hilt:hilt-work:1.2.0")
    ksp("androidx.hilt:hilt-compiler:1.2.0")

    // DataStore (Preferences)
    implementation("androidx.datastore:datastore-preferences:1.1.1")

    // EPUB Reading (Readium)
    implementation("org.readium.kotlin-toolkit:readium-shared:3.1.2")
    implementation("org.readium.kotlin-toolkit:readium-streamer:3.1.2")
    implementation("org.readium.kotlin-toolkit:readium-navigator:3.1.2")
    
    // Image loading (cover art in cards)
    implementation("io.coil-kt:coil-compose:2.7.0")

    // HTML Parsing
    implementation("org.jsoup:jsoup:1.17.2")

    // Testing
    testImplementation("junit:junit:4.13.2")
    // mockk mocks final Kotlin classes (NetworkMonitor, TokenManager) and suspend
    // functions, which is what makes ViewModels unit-testable off-device.
    testImplementation("io.mockk:mockk:1.14.2")
    // Counts requests, which is what the refresh-recursion bug is about
    // (issue #143): a unit test can assert "exactly one refresh POST" in a way
    // a mocked Chain cannot.
    testImplementation("com.squareup.okhttp3:mockwebserver:4.12.0")
    // Real SQLite in JVM unit tests, so MIGRATION_19_20 can actually be executed
    // against a populated v19 database (issue #314). Room's MigrationTestHelper
    // needs an instrumentation context and this module has no androidTest source
    // set, so CI would never run it; this does the same job on the JVM.
    testImplementation("org.xerial:sqlite-jdbc:3.50.3.0")
    // Version must track the kotlinx-coroutines-core the app resolves to (1.10.2) —
    // a mismatch breaks Dispatchers.setMain.
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.10.2")
    androidTestImplementation("androidx.test.ext:junit:1.2.1")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.6.1")
    androidTestImplementation(platform("androidx.compose:compose-bom:2025.05.00"))
    androidTestImplementation("androidx.compose.ui:ui-test-junit4")
    debugImplementation("androidx.compose.ui:ui-tooling")
    debugImplementation("androidx.compose.ui:ui-test-manifest")

    // Core library desugaring (required by Readium)
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.5")
}

// Mirror the shared cross-platform sync-parity fixtures (single source of truth:
// the server) into the unit-test resources so SyncMatcherParityTest can load them.
// rootDir is the android/ project; the server lives one level up in the repo.
val copySyncParityFixtures by tasks.registering(Copy::class) {
    from("$rootDir/../server/tests/fixtures/sync_parity")
    into(layout.projectDirectory.dir("src/test/resources/sync_parity"))
}
tasks.named("preBuild") { dependsOn(copySyncParityFixtures) }
tasks.withType<Test>().configureEach { dependsOn(copySyncParityFixtures) }

// Coverage floor for the JVM unit tests (issue #95), mirroring the server's
// --cov-fail-under and the web module's vitest thresholds. Anti-backslide only: the
// number is deliberately a few points under the measured total, and gets ratcheted up
// as coverage grows. See docs/testing.md ("Android") for the policy and the exclusion
// rationale. Tasks: :app:koverXmlReportDebug, :app:koverVerifyDebug.
kover {
    reports {
        filters {
            excludes {
                classes(
                    // --- Generated code ---
                    "*_Factory",
                    "*_Factory\$*",
                    "*_MembersInjector",
                    "*Hilt_*",
                    "*_HiltModules*",
                    "*_GeneratedInjector",
                    "*_ComponentTreeDeps",
                    "dagger.hilt.internal.aggregatedroot.codegen.*",
                    "hilt_aggregated_deps.*",
                    "com.booksync.BuildConfig",
                    "com.booksync.R",
                    "com.booksync.R\$*",
                    "*ComposableSingletons*",
                    "*\$\$serializer",
                    "*_Impl",
                    "*_Impl\$*",

                    // --- Compose UI: no emulator or Robolectric in CI, so screens,
                    // components, theme and navigation are untestable today. ViewModels
                    // under ui/ are deliberately NOT excluded — they are the main
                    // backfill target.
                    "com.booksync.ui.*Screen*",
                    "com.booksync.ui.components.*",
                    "com.booksync.ui.theme.*",
                    "com.booksync.ui.BookSyncNavigation*",
                    "com.booksync.ui.reader.ReaderActivity*",
                    "com.booksync.ui.reader.DictionarySheet*",
                    "com.booksync.ui.player.UnifiedAudioPlayer*",
                    "com.booksync.ui.account.ChangePasswordSheet*",
                    "com.booksync.MainActivity*",
                    "com.booksync.BookSyncApp*",

                    // --- Android framework / service glue with no JVM-testable surface
                    // (same reasoning as the server excluding ffmpeg/hardware glue).
                    "com.booksync.player.AudioPlayerService*",
                    "com.booksync.player.LocalCastHttpServer*",
                    "com.booksync.cast.*",
                    "com.booksync.auto.*",
                    "com.booksync.di.*",
                    "com.booksync.data.local.BookSyncDatabase*",
                )
            }
        }
        verify {
            rule {
                bound {
                    // Measured 48.55% line coverage on 2026-09-03 (2020/4161 lines);
                    // floor set a few points under, same as the server's --cov-fail-under.
                    // Ratchet: after any PR that raises the total, bump this to
                    // (new total − 3), whole percent.
                    //
                    // The previous baseline (43.86%, 1722/3926) was measured earlier the
                    // same day, before the first-run screen of issue #175 landed — which
                    // is where most of the jump comes from, not from issue #174.
                    minValue = 45
                    coverageUnits = CoverageUnit.LINE
                }
            }
        }
    }
}
